skip_tags: true

cache:
- WebJobAppevyor\packages -> **\packages.config

configuration: Release

build:
  publish_wap: true

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: AccountInBank v$(appveyor_build_version)
  auth_token:
    secure: r9lnQ5IoCZfhxiWzQDjPKpXQthKNMpFzMeRZhCq8eBC3fY8WhZjKwsrdBjEawqRn
  draft: true
