#os: unstable

# Fix line endings in Windows. (runs before repo cloning)
init:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

configuration: Release

build:
  publish_wap: true
